#!/bin/bash
# Prints the passwords file
#awk -F ":" 'NR==10,NR==100 { print $1, $3 } ' /etc/passwd
#awk -F ":" 'NR==10,NR==100 { print length($1), $3 } ' /etc/passwd
#awk -F ":" '{ printf "%-20s %3d\n", $1, $3 } ' /etc/passwd
awk -F ":" '
BEGIN { printf "%-20s %-3s\n", "USER", "UID" }
{ printf "%-20s %3d\n", $1, $3 } ' /etc/passwd
